runtime: python312

# Add Cloud SQL Proxy handler
handlers:
- url: /cloudsql
  script: auto

entrypoint: gunicorn -b :$PORT trastero.wsgi
beta_settings:
  cloud_sql_instances: trastero-postgres
env_variables:
  DJANGO_ENV: 'production'
  DB_HOST: 35.240.85.77
  DB_NAME: $DB_NAME
  DB_USER: $DB_USER
  DB_PASSWORD: $DB_PASSWORD