version: '3.9'

services:

# The proxy will help us connect to remote CloudSQL instance locally.
# Make sure to turn off any VPNs for the proxy to work.
  cloudsqlproxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    volumes:
      - ./creds.json:/secrets/cloudsql/creds.json
    ports:
      - 5432:5432
    command: /cloud_sql_proxy -instances="el-trastero-de-adri:europe-west1:trastero-postgres"=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/creds.json
    restart: always

  server:
    container_name: el-trastero-de-adri
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./creds.json:/secrets/creds.json
    ports:
      - 8080:8080
    env_file:
      - ./.env
    restart: always
    depends_on:
      - cloudsqlproxy
